baseURL = 'https://chagu.org/'
languageCode = 'en-us'
title = 'ChaGu CTF'
theme = "cactus"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Writeups"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4


[params]
    mainSectionTitle = "Writeups"
    showAllPostsOnHomePage = false
    postsOnHomePage = 5
    rss = true
    showReadTime = true
    showAllPostsArchive = false